### ISSUE TITLE
Contribution workflow and usefulness of staging branches

### ISSUE THREAD

**Issue by spudowiar** [vktec/vKTec-IRC-Code-of-Conduct#5]
Personally, I find the use of the staging branch `devel` superfluous and inconsistent with the type of project here

Thoughts?

**Comment by vktec** [comment]
My thinking on creating the `devel` branch was that it would allow us to work on and fine tune changes before merging to `master`, but I now agree that it seems unnecessary, and can simply be done using PRs.

**Comment by spudowiar** [comment]
In my opinion a staging is totally irrelevant to the actual merging but rather is for a certain type of software (website, for example) that needs isolated testing before being rolled out to production.

**Comment by vktec** [comment]
Yes, I agree.

**Comment by vktec** [comment]
I will remove the `devel` branch and edit the CONTRIBUTING file accordingly.
